name: Deploy .NET Aspire project to Raspberry Pi 5 with Docker

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t aspire-firesteel-image:latest .

      - name: Stop old Docker container
        run: |
          docker stop aspire-firesteel || true
          docker rm aspire-firesteel || true
          
      # The port 16003 is used by cloudflare tunnel to display dashboard
      # The other ports are used by .NET Aspire
      - name: Run new Docker container
        run: |
          docker run -d --name aspire-firesteel \
            --restart unless-stopped \
            -p 16003:16003 \
            -p 19238:19238 \
            -p 20237:20237 \
            aspire-firesteel-image:latest
